./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT DISTINCT ?product ?label WHERE { ?product rdfs:label ?label . ?product a bsbm-inst:ProductType1 . ?product bsbm:productFeature bsbm-inst:ProductFeature60 . ?product bsbm:productFeature bsbm-inst:ProductFeature74 . ?product bsbm:productPropertyNumeric1 ?value1 . FILTER (?value1 > 1) } ORDER BY ?label LIMIT 10" > /data/outputq1.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX bsbm-prod:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/> SELECT ?label ?comment ?producer ?productFeature ?propertyTextual1 ?propertyTextual2 ?propertyTextual3 ?propertyNumeric1 ?propertyNumeric2 ?propertyTextual4 ?propertyTextual5 ?propertyNumeric4 WHERE { bsbm-prod:Product1 rdfs:label ?label .	bsbm-prod:Product1 rdfs:comment ?comment . bsbm-prod:Product1 bsbm:producer ?p . ?p rdfs:label ?producer . bsbm-prod:Product1 dc:publisher ?p . bsbm-prod:Product1 bsbm:productFeature ?f . ?f rdfs:label ?productFeature . bsbm-prod:Product1 bsbm:productPropertyTextual1 ?propertyTextual1 . bsbm-prod:Product1 bsbm:productPropertyTextual2 ?propertyTextual2 . bsbm-prod:Product1 bsbm:productPropertyTextual3 ?propertyTextual3 . bsbm-prod:Product1 bsbm:productPropertyNumeric1 ?propertyNumeric1 .	bsbm-prod:Product1 bsbm:productPropertyNumeric2 ?propertyNumeric2 . OPTIONAL { bsbm-prod:Product1 bsbm:productPropertyTextual4 ?propertyTextual4 } OPTIONAL { bsbm-prod:Product1 bsbm:productPropertyTextual5 ?propertyTextual5 } OPTIONAL { bsbm-prod:Product1 bsbm:productPropertyNumeric4 ?propertyNumeric4 } }" > /data/outputq2.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT ?product ?label WHERE { ?product rdfs:label ?label . ?product a bsbm-inst:ProductType1 . ?product bsbm:productFeature bsbm-inst:ProductFeature60 . ?product bsbm:productPropertyNumeric1 ?p1 . FILTER ( ?p1 > 5 ) ?product bsbm:productPropertyNumeric3 ?p3 .	FILTER (?p3 < 1 ) MINUS { ?product bsbm:productFeature bsbm-inst:ProductFeature69 . ?product rdfs:label ?testVar  } } ORDER BY ?label LIMIT 10" > /data/outputq3.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> SELECT DISTINCT ?product ?label ?propertyTextual WHERE { {  ?product rdfs:label ?label . ?product rdf:type bsbm-inst:ProductType1 . ?product bsbm:productFeature bsbm-inst:ProductFeature60 . ?product bsbm:productFeature bsbm-inst:ProductFeature61 . ?product bsbm:productPropertyTextual1 ?propertyTextual .	?product bsbm:productPropertyNumeric1 ?p1 .	FILTER ( ?p1 > 1 ) } UNION { ?product rdfs:label ?label . ?product rdf:type bsbm-inst:ProductType2 . ?product bsbm:productFeature bsbm-inst:ProductFeature2 . ?product bsbm:productFeature bsbm-inst:ProductFeature4 . ?product bsbm:productPropertyTextual1 ?propertyTextual .	?product bsbm:productPropertyNumeric2 ?p2 .	FILTER ( ?p2> 2 ) } } ORDER BY ?label OFFSET 5 LIMIT 10" > /data/outputq4.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX bsbm-prod:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/> SELECT DISTINCT ?product ?productLabel WHERE { ?product rdfs:label ?productLabel . FILTER (bsbm-prod:Product16 != ?product)	bsbm-prod:Product16 bsbm:productFeature ?prodFeature . ?product bsbm:productFeature ?prodFeature . bsbm-prod:Product16 bsbm:productPropertyNumeric1 ?origProperty1 . ?product bsbm:productPropertyNumeric1 ?simProperty1 . FILTER (?simProperty1 < (?origProperty1 + 120) && ?simProperty1 > (?origProperty1 - 120)) bsbm-prod:Product16 bsbm:productPropertyNumeric2 ?origProperty2 . ?product bsbm:productPropertyNumeric2 ?simProperty2 . FILTER (?simProperty2 < (?origProperty2 + 170) && ?simProperty2 > (?origProperty2 - 170)) } ORDER BY ?productLabel LIMIT 5" > /data/outputq5.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> SELECT ?product ?label WHERE {	?product rdfs:label ?label . ?product rdf:type bsbm:Product . FILTER regex(?label,\"reducing\") }" > /data/outputq6.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rev: <http://purl.org/stuff/rev#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX bsbm-prod: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer33/> SELECT ?productLabel ?offer ?price ?vendor ?vendorTitle ?review ?revTitle ?reviewer ?revName ?rating1 ?rating2 WHERE { bsbm-prod:Product1518 rdfs:label ?productLabel . OPTIONAL { ?offer bsbm:product bsbm-prod:Product1518 . ?offer bsbm:price ?price .	?offer bsbm:vendor ?vendor . ?vendor rdfs:label ?vendorTitle . ?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#DE> . ?offer dc:publisher ?vendor . ?offer bsbm:validTo ?date . FILTER (?date > 2008 ) } OPTIONAL { ?review bsbm:reviewFor bsbm-prod:Product1518 . ?review rev:reviewer ?reviewer . ?reviewer foaf:name ?revName . ?review dc:title ?revTitle . OPTIONAL { ?review bsbm:rating1 ?rating1 . } OPTIONAL { ?review bsbm:rating2 ?rating2 . } } }" > /data/outputq7.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX rev: <http://purl.org/stuff/rev#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX bsbm-prod: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer33/> SELECT ?title ?text ?reviewDate ?reviewer ?reviewerName ?rating1 ?rating2 ?rating3 ?rating4 WHERE { ?review bsbm:reviewFor bsbm-prod:Product1518 . ?review dc:title ?title . ?review rev:text ?text . FILTER langMatches( lang(?text), \"EN\" ) ?review bsbm:reviewDate ?reviewDate . ?review rev:reviewer ?reviewer . ?reviewer foaf:name ?reviewerName . OPTIONAL { ?review bsbm:rating1 ?rating1 . } OPTIONAL { ?review bsbm:rating2 ?rating2 . } OPTIONAL { ?review bsbm:rating3 ?rating3 . } OPTIONAL { ?review bsbm:rating4 ?rating4 . } } ORDER BY DESC(?reviewDate) LIMIT 20" > /data/outputq8.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX rev: <http://purl.org/stuff/rev#> PREFIX reviewer: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromRatingSite1/> DESCRIBE ?x WHERE { reviewer:Reviewer1 rev:reviewer ?x }" > /data/outputq9.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX bsbm-prod: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer33/> SELECT DISTINCT ?offer ?price WHERE { ?offer bsbm:product bsbm-prod:Product1518. ?offer bsbm:vendor ?vendor . ?offer dc:publisher ?vendor . ?vendor bsbm:country <http://downlode.org/rdf/iso-3166/countries#US> .	?offer bsbm:deliveryDays ?deliveryDays . FILTER (?deliveryDays <= 3) ?offer bsbm:price ?price . ?offer bsbm:validTo ?date . FILTER (?date > 2008 ) } ORDER BY xsd:double(str(?price)) LIMIT 10" > /data/outputq10.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX offer:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromVendor1/> SELECT ?property ?hasValue ?isValueOf WHERE { { offer:Offer1 ?property ?hasValue } UNION { ?isValueOf ?property offer:Offer1 } }" > /data/outputq11.txt

./bin/hdtsparql.sh /data/berlin100000.hdt "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rev: <http://purl.org/stuff/rev#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> PREFIX bsbm-export: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/export/> PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX offer:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromVendor1/> CONSTRUCT { offer:Offer1 bsbm-export:product ?productURI . offer:Offer1 bsbm-export:productlabel ?productlabel . offer:Offer1 bsbm-export:vendor ?vendorname . offer:Offer1 bsbm-export:vendorhomepage ?vendorhomepage . offer:Offer1 bsbm-export:offerURL ?offerURL . offer:Offer1 bsbm-export:price ?price . offer:Offer1 bsbm-export:deliveryDays ?deliveryDays . offer:Offer1 bsbm-export:validuntil ?validTo } WHERE { offer:Offer1 bsbm:product ?productURI . ?productURI rdfs:label ?productlabel . offer:Offer1 bsbm:vendor ?vendorURI . ?vendorURI rdfs:label ?vendorname . ?vendorURI foaf:homepage ?vendorhomepage . offer:Offer1 bsbm:offerWebpage ?offerURL . offer:Offer1 bsbm:price ?price . offer:Offer1 bsbm:deliveryDays ?deliveryDays . offer:Offer1 bsbm:validTo ?validTo }" > /data/outputq12.txt
