/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection */

#ifndef _Included_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
#define _Included_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
#ifdef __cplusplus
extern "C" {
#endif
#undef org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection_TYPE_INDEX
#define org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection_TYPE_INDEX 2L
#undef org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection_DEFAULT_BLOCK_SIZE
#define org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection_DEFAULT_BLOCK_SIZE 16L
/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
 * Method:    _writeJNIDictionary
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection__1writeJNIDictionary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
 * Method:    _createJNIDictionary
 * Signature: ([BILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection__1createJNIDictionary
  (JNIEnv *, jobject, jbyteArray, jint, jstring);

/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
 * Method:    locate
 * Signature: (Ljava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection_locate
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
 * Method:    extract
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection_extract
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
 * Method:    _loadJNIDictionary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection__1loadJNIDictionary__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
 * Method:    _saveJNIDictionary
 * Signature: (Ljava/io/OutputStream/String;)V
 */
JNIEXPORT void JNICALL Java_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection__1saveJNIDictionary
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif