/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection */

#ifndef _Included_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
#define _Included_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection
 * Method:    _writeJNIDictionary
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_rdfhdt_hdt_dictionary_impl_section_JNIDictionarySection__1writeJNIDictionary
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
