/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rdfhdt_hdt_dictionary_impl_FourSectionDictionary */

#ifndef _Included_org_rdfhdt_hdt_dictionary_impl_FourSectionDictionary
#define _Included_org_rdfhdt_hdt_dictionary_impl_FourSectionDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rdfhdt_hdt_dictionary_impl_FourSectionDictionary
 * Method:    _writeDictionary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_rdfhdt_hdt_dictionary_impl_FourSectionDictionary__1writeDictionary
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
