/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rdfhdt_hdt_triples_impl_K2Triples */

#ifndef _Included_org_rdfhdt_hdt_triples_impl_K2Triples
#define _Included_org_rdfhdt_hdt_triples_impl_K2Triples
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    _createK2Triples
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples__1createK2Triples
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    _loadK2Triples
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples__1loadK2Triples
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    _storeK2Triples
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples__1storeK2Triples
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    _destroyK2Triples
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples__1destroyK2Triples
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    _sizeK2Triples
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples__1sizeK2Triples
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    doSearchK2Triples
 * Signature: (JIII)[I
 */
JNIEXPORT jintArray JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_doSearchK2Triples
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    searchSPO
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_searchSPO
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    searchSP
 * Signature: (JII)[I
 */
JNIEXPORT jintArray JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_searchSP
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    searchPO
 * Signature: (JII)[I
 */
JNIEXPORT jintArray JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_searchPO
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    searchSO
 * Signature: (JII)[I
 */
JNIEXPORT jintArray JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_searchSO
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    searchS
 * Signature: (JI)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_searchS
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    searchP
 * Signature: (JI)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_searchP
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    searchO
 * Signature: (JI)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_searchO
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_rdfhdt_hdt_triples_impl_K2Triples
 * Method:    getNPreds
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_rdfhdt_hdt_triples_impl_K2Triples_getNPreds
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
